FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git unzip zip libpq-dev && \
    docker-php-ext-install pdo_pgsql

COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install

RUN chown -R www-data:www-data /app

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
